### ISSUE TITLE
Add parameters validation 

### ISSUE THREAD

**Issue by scriptprinter** [zvibazak/termshape#10]
When i use a negative value, such as `get_square(-5, -5)`:
`ValueError: min() arg is an empty sequence` is raised.

Is something relationated with this lines:
```python
# calc min_x, min_y for range with negative values
min_x = abs(min(list_x))
min_y = abs(min(list_y))
```
in the function `make_shape()`.

And I don't think if is allowed to use a negative number.

**Comment by zvibazak** [comment]
- `get_square()` expects 1 parameter.
-  as you wrote there is no logic in negative number as length... 

So need to add validation...

**Comment by scriptprinter** [comment]
That is true, big mistake i made XD
I thinked that is two paramaters like `get_rectangle()`

**Comment by zvibazak** [comment]
Done on version 1.0.0
