### ISSUE TITLE
Idea for a "custom" shape implementation

### ISSUE THREAD

**Issue by scriptprinter** [zvibazak/termshape#5]
The function has 5 parameteres.

`width`, `height`, `start_x`, `start_y` and `lines`.

The function creates an empty canvas of `width` x `height`.
And start drawings the `lines` x and y from `start_x` and `start_y`.

## Example
```
termshape.custom(10, 10, 0, 0, [(5, 5), (5, 2), (7, 8)])

   X 0  1  2  3  4  5  6  7  8  9
Y
0    *  -  -  -  -  -  -  -  -  -                           
1    -  *  -  -  -  -  -  -  -  -                            
2    -  -  *  -  -  *  -  -  -  -              
3    -  -  -  *  -  *  *  -  -  -           
4    -  -  -  -  *  *  -  *  -  -
5    -  -  -  -  -  *  -  *  -  -
6    -  -  -  -  -  -  -  *  -  -      
7    -  -  -  -  -  -  -  *  -  -
8    -  -  -  -  -  -  -  *  -  -                           
9    -  -  -  -  -  -  -  -  -  -
```
**Observation:** the `'-'` is a space by default (`' '`), this is just to better style.
I don't know if I explained right, but for any questions, create a comment.

**Comment by zvibazak** [comment]
Nice idea.. :+1:
I have some other ideas of improving, you're welcome to implement yours.

**Comment by scriptprinter** [comment]
@zvibazak You are placing this in the PEP?

**Comment by zvibazak** [comment]
Are you still here scriptprinter ? 
I wish you continue to contribute if you wish...

Thanks a lot for your work anyway...

**Comment by scriptprinter** [comment]
I have an ideia to make this shape, the function create an array of all the points and use the shape `get_points()`.
i will try this.

**Comment by scriptprinter** [comment]
After you view the pull request #16 
I will make another with the implementation of the `get_lines()` function and some others changes.

```python
print(termshape.get_lines(10, 10, [(0, 0), (9, 9), (0, 0), (9, 0), (0, 9), (9, 9)], fg='@', bg='-'))
```
```
@ @ @ @ @ @ @ @ @ @
- @ - - - - - - @ -
- - @ - - - - @ - -
- - - @ - - @ - - -
- - - - @ @ - - - -
- - - - @ @ - - - -
- - - @ - - @ - - -
- - @ - - - - @ - -
- @ - - - - - - @ -
@ @ @ @ @ @ @ @ @ @
```

@zvibazak 

**Edit**: A better test with the same result:
```python
print(termshape.get_lines(10, 10, [(0, 0), (9, 9), (0, 9), (9, 0), (0, 0)], fg='@', bg='-'))
```
**Another edit:** The parameters `start_x` and `start_y` is now the first item of the array `lines`.

**Comment by scriptprinter** [comment]
The `get_lines()` came with the pull request #17
